"""Count modeled DDIO/LLC violations for generated address lists (Figure 10).

This script reads address lists generated by:
- `gen_stride1_address_list.py`
- `gen_tetris_address_list.py`

For each address it computes the LLC slice number (via `hash_function.py`) and a
set index, then builds a (slice, set) histogram. It reports:
- Miss/violation rate: fraction of accesses where the (slice, set) bucket count
    exceeds `config.THRESHOLD`.
- Per-access-count ratios for counts 0..THRESHOLD.

Outputs:
- data/counter/<pattern>_<workingset_kb>.txt
"""

import config
import numpy as np
import hash_function
import os

access_pattern_types = ["tetris", "stride1"]
workingset_size_kb_list = [4096, 5120, 5632, 6656]

def calculate_miss_rate(address_list, slice_nums):
    # Total number of LLC sets modeled across all page groups.
    TOTAL_SETS      = config.N_SETS * config.NUM_PAGE_GROUPS
    cache_struct    = np.zeros(TOTAL_SETS * config.N_SLICES, dtype=int)

    for address, slice_num in zip(address_list, slice_nums):
        # LLC set index (using 64B line granularity).
        set_index = int((address >> 6) & (TOTAL_SETS-1))
        cache_struct[TOTAL_SETS*slice_num + set_index] += 1
    
    miss_rate = (np.sum(cache_struct[cache_struct > config.THRESHOLD]) / len(address_list)) * 100
    
    access_ratio_per_access_count = {}
    
    for i in range(config.THRESHOLD+1):
        access_ratio_per_access_count[i] = (np.sum(cache_struct[cache_struct == i]) / len(address_list))*100

    return (miss_rate, access_ratio_per_access_count, )

output_dir = f"data/counter"
os.makedirs(output_dir, exist_ok=True)

for workingset_size_kb in workingset_size_kb_list:
    print(f"=================={workingset_size_kb}kb==================")
    for access_pattern_type in access_pattern_types:
        file_name = f"data/address_list-{access_pattern_type}/address_list.{workingset_size_kb}.csv"
        with open(file_name, "r") as f:
            address_list = np.array(list(map(lambda x: int(x, 16), f.read().strip().split('\n'))), dtype=np.uint64)
        slice_nums = hash_function.get_slice_nums(address_list)
        miss_rate, access_ratio_per_access_count = calculate_miss_rate(address_list, slice_nums)
        print(f"\t{access_pattern_type}-miss_rate: {miss_rate:.2f}%")
        for count, value in access_ratio_per_access_count.items():
            print(f"\t{access_pattern_type}-count_{count}: {value:.2f}%")

        output_file_name = f"{output_dir}/{access_pattern_type}_{workingset_size_kb}.txt"
        with open(output_file_name, "w") as f:
            for i in range(config.THRESHOLD+1):
                print(f"{i}:{access_ratio_per_access_count[i]:.2f}", file=f)
        
