"""Create a per-group Tetris page-index sequence (Figure 10).

This script post-processes the long (pattern/page_index) sequences generated by
`block_tetris.py`. For each page group, it selects a contiguous block of page
indices and stores it under `tetris_page_index_sequence/`.

Inputs (per page group):
- data/tetris_data-.../pattern_sequence/page_group_index_<i>.pkl
- data/tetris_data-.../page_index_sequence/page_group_index_<i>.pkl

Output:
- data/tetris_data-.../tetris_page_index_sequence/page_group_index_<i>.pkl

Usage:
    python3 py_scripts/create_page_index_sequence.py <page_group_index>
"""

import pickle
import sys
import numpy as np
import matplotlib.pyplot as plt
import os
import config

page_group_index = int(sys.argv[1])

N_SETS              = config.N_SETS
N_SLICES            = config.N_SLICES
TARGET_UNIT_PAGES   = config.TARGET_UNIT_PAGES
TOTAL_ACCESS        = N_SETS * TARGET_UNIT_PAGES

output_dir = f"data/tetris_data-{config.START_ADDRESS_HEX}-{config.TARGET_UNIT_PAGES}"
pattern_sequence_dir    = f"{output_dir}/pattern_sequence"
page_index_sequence_dir = f"{output_dir}/page_index_sequence"
try:
    with open(f"{output_dir}/page_index_table.pkl", "rb") as file:
        page_index_table = dict(pickle.load(file)[page_group_index])
        pattern_list     = list(page_index_table.keys())

    with open(f"{pattern_sequence_dir}/page_group_index_{page_group_index}.pkl", "rb") as file:
        pattern_sequence = list(pickle.load(file))
    with open(f"{page_index_sequence_dir}/page_group_index_{page_group_index}.pkl", "rb") as file:
        page_index_sequence = pickle.load(file)

except Exception as e:
    print(e.with_traceback(None))
    print("There is no sequence.")
    exit(-1)


def calculate_miss_rate(patterns):
    # Create a counter array
    counter = np.zeros(N_SETS * N_SLICES, dtype=int)

    # Convert patterns to a NumPy array for efficient indexing
    patterns = np.array(patterns)

    # Compute indices in a vectorized manner
    indices = N_SETS * patterns + np.arange(N_SETS)

    # Use NumPy's add.at() to efficiently increment the counter
    np.add.at(counter, indices.ravel(), 1)

    # Calculate the miss rate
    miss_rate = np.sum(counter[counter > config.THRESHOLD]) / TOTAL_ACCESS
    return round(miss_rate, 6)


TOTAL_N_PAGES = ((128 // TARGET_UNIT_PAGES) + 1) * TARGET_UNIT_PAGES
half_size = TARGET_UNIT_PAGES // 2

x_values = []
y_values = []
for start_index, end_index in enumerate(range(TOTAL_N_PAGES-half_size, len(pattern_sequence)-half_size)):
    # Evaluate a window by combining its first/last half blocks.
    test_target = pattern_sequence[start_index:start_index+half_size] + pattern_sequence[end_index:end_index+half_size]

    miss_rate = calculate_miss_rate(test_target) * 100
    x_values.append(start_index)
    y_values.append(miss_rate)

good_block_index = np.argmin(y_values)
good_start_index = x_values[good_block_index]
good_miss_rate   = y_values[good_block_index]
good_block = page_index_sequence[good_start_index:good_start_index+TOTAL_N_PAGES]

tetris_page_index_sequence_dir = f"{output_dir}/tetris_page_index_sequence"
os.makedirs(tetris_page_index_sequence_dir, exist_ok=True)
with open(f"{tetris_page_index_sequence_dir}/page_group_index_{page_group_index}.pkl", "wb") as file:
    pickle.dump(good_block, file)
print(f"{page_group_index:2d}: {good_miss_rate:.2f}%")